# Generated by Django 5.1 on 2024-08-13 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0002_compras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='compras',
        ),
    ]
