# Generated by Django 5.1 on 2024-08-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0003_delete_compras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task',
        ),
    ]
