# Generated by Django 5.1 on 2024-08-14 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0006_rename_clientes_cliente_rename_compras_compra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
