# Generated by Django 5.1 on 2024-08-14 13:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0008_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='compra',
            new_name='stock',
        ),
    ]
