# Generated by Django 5.1 on 2024-08-17 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0014_remove_compra_usuario_remove_detallecompra_compra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto_Tienda',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptops.cliente_tienda')),
            ],
        ),
    ]
